import nodemailer from 'nodemailer';
import { env } from '../config/env.js';
import { logger } from '../utils/logger.js';

let transporter;

const setupTransporter = async () => {
  if (transporter) return transporter;

  if (env.EMAIL_HOST && env.EMAIL_USER && env.EMAIL_PASSWORD) {
    try {
      transporter = nodemailer.createTransport({
        host: env.EMAIL_HOST,
        port: env.EMAIL_PORT || 587,
        secure: env.EMAIL_PORT === 465,
        auth: {
          user: env.EMAIL_USER,
          pass: env.EMAIL_PASSWORD
        },
        connectionTimeout: 4000, // 4 seconds max timeout
        greetingTimeout: 4000,
        socketTimeout: 4000
      });
      return transporter;
    } catch (err) {
      logger.warn('📧 Real SMTP Transporter setup failed, falling back to mock logger:', err.message);
    }
  }

  // Fallback dev/logger transporter
  logger.info('📧 Configured mock/log email transporter for development.');
  transporter = nodemailer.createTransport({
    jsonTransport: true
  });
  return transporter;
};

export const sendPurchaseOrderEmail = async ({
  supplierEmail,
  supplierName,
  poId,
  productName,
  sku,
  quantity,
  unitCost,
  totalCost
}) => {
  try {
    const mailer = await setupTransporter();
    const mailOptions = {
      from: env.EMAIL_FROM,
      to: supplierEmail,
      subject: `OFFICIAL PURCHASE ORDER #${poId} - ${productName}`,
      html: `
        <div style="font-family: Arial, sans-serif; padding: 20px; color: #333; max-width: 600px; border: 1px solid #e2e8f0; border-radius: 8px;">
          <h2 style="color: #2563eb;">StockPilot - Purchase Order #${poId}</h2>
          <p>Dear <strong>${supplierName}</strong>,</p>
          <p>Please accept this official purchase order for inventory replenishment.</p>
          
          <table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
            <tr style="background-color: #f8fafc; border-bottom: 2px solid #e2e8f0;">
              <th style="padding: 10px; text-align: left;">Item Details</th>
              <th style="padding: 10px; text-align: right;">Value</th>
            </tr>
            <tr>
              <td style="padding: 8px; border-bottom: 1px solid #edf2f7;"><strong>Product Name:</strong></td>
              <td style="padding: 8px; border-bottom: 1px solid #edf2f7; text-align: right;">${productName}</td>
            </tr>
            <tr>
              <td style="padding: 8px; border-bottom: 1px solid #edf2f7;"><strong>SKU:</strong></td>
              <td style="padding: 8px; border-bottom: 1px solid #edf2f7; text-align: right;">${sku}</td>
            </tr>
            <tr>
              <td style="padding: 8px; border-bottom: 1px solid #edf2f7;"><strong>Order Quantity:</strong></td>
              <td style="padding: 8px; border-bottom: 1px solid #edf2f7; text-align: right;">${quantity} units</td>
            </tr>
            <tr>
              <td style="padding: 8px; border-bottom: 1px solid #edf2f7;"><strong>Unit Cost:</strong></td>
              <td style="padding: 8px; border-bottom: 1px solid #edf2f7; text-align: right;">$${Number(unitCost).toFixed(2)}</td>
            </tr>
            <tr style="font-weight: bold; background-color: #eff6ff;">
              <td style="padding: 10px; color: #1e40af;"><strong>Total Order Amount:</strong></td>
              <td style="padding: 10px; color: #1e40af; text-align: right;">$${Number(totalCost).toFixed(2)}</td>
            </tr>
          </table>

          <p>Please confirm receipt of this order and reply with estimated delivery details.</p>
          <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 20px 0;" />
          <p style="font-size: 12px; color: #64748b;">This email was automatically generated by StockPilot Inventory Restock Agent.</p>
        </div>
      `
    };

    const info = await mailer.sendMail(mailOptions);
    logger.info(`📧 Purchase Order Email dispatched to ${supplierEmail}:`, info.messageId || info.response || 'Dispatched');
    return { success: true, info };
  } catch (error) {
    logger.warn(`📧 SMTP dispatch timed out/failed for ${supplierEmail}: ${error.message}`);
    return { success: false, error: error.message };
  }
};

/**
 * Send Vendor RFP Award / Negotiation Email
 */
export const sendVendorProposalEmail = async ({
  to,
  vendorName,
  subject,
  content
}) => {
  try {
    const mailer = await setupTransporter();
    const recipient = to || 'vendor@example.com';
    const emailSubject = subject || `StockPilot Sourcing RFP Award & Next Steps - ${vendorName}`;

    const mailOptions = {
      from: env.EMAIL_FROM,
      to: recipient,
      subject: emailSubject,
      text: content,
      html: `
        <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; padding: 24px; color: #1e293b; max-width: 650px; border: 1px solid #e2e8f0; border-radius: 12px; background: #ffffff; margin: 0 auto;">
          <div style="border-bottom: 2px solid #3b82f6; padding-bottom: 12px; margin-bottom: 20px;">
            <h2 style="color: #1e40af; margin: 0; font-size: 20px;">StockPilot Procurement & Supply Chain</h2>
            <p style="color: #64748b; font-size: 13px; margin: 4px 0 0 0;">Official Vendor RFP Communication</p>
          </div>
          
          <div style="white-space: pre-wrap; font-size: 14px; line-height: 1.6; color: #334155; margin-bottom: 24px;">
${content.replace(/</g, '&lt;').replace(/>/g, '&gt;')}
          </div>

          <div style="background-color: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 12px; font-size: 12px; color: #64748b;">
            <p style="margin: 0;"><strong>Recipient:</strong> ${vendorName} &lt;${recipient}&gt;</p>
            <p style="margin: 4px 0 0 0;">Sent autonomously via StockPilot Supplier Intelligence AI Platform.</p>
          </div>
        </div>
      `
    };

    const info = await mailer.sendMail(mailOptions);
    logger.info(`📧 Vendor proposal email dispatched to ${recipient}: ${info.messageId || 'mock'}`);
    return { success: true, messageId: info.messageId || 'mock_sent', recipient };
  } catch (error) {
    logger.warn(`📧 Vendor email dispatch failed for ${to}: ${error.message}`);
    return { success: false, error: error.message };
  }
};
