import nodemailer from 'nodemailer';
import { env } from '../config/env.js';
import { logger } from '../utils/logger.js';

let transporter;

const setupTransporter = async () => {
  if (transporter) return transporter;

  if (env.EMAIL_HOST && env.EMAIL_USER && env.EMAIL_PASSWORD) {
    try {
      transporter = nodemailer.createTransport({
        host: env.EMAIL_HOST,
        port: env.EMAIL_PORT || 587,
        secure: env.EMAIL_PORT === 465,
        auth: {
          user: env.EMAIL_USER,
          pass: env.EMAIL_PASSWORD
        },
        connectionTimeout: 4000, // 4 seconds max timeout
        greetingTimeout: 4000,
        socketTimeout: 4000
      });
      return transporter;
    } catch (err) {
      logger.warn('📧 Real SMTP Transporter setup failed, falling back to mock logger:', err.message);
    }
  }

  // Fallback dev/logger transporter
  logger.info('📧 Configured mock/log email transporter for development.');
  transporter = nodemailer.createTransport({
    jsonTransport: true
  });
  return transporter;
};

export const sendPurchaseOrderEmail = async ({
  supplierEmail,
  supplierName,
  poId,
  productName,
  sku,
  quantity,
  unitCost,
  totalCost
}) => {
  try {
    const mailer = await setupTransporter();
    const mailOptions = {
      from: env.EMAIL_FROM,
      to: supplierEmail,
      subject: `OFFICIAL PURCHASE ORDER #${poId} - ${productName}`,
      html: `
        <div style="font-family: Arial, sans-serif; padding: 20px; color: #333; max-width: 600px; border: 1px solid #e2e8f0; border-radius: 8px;">
          <h2 style="color: #2563eb;">StockPilot - Purchase Order #${poId}</h2>
          <p>Dear <strong>${supplierName}</strong>,</p>
          <p>Please accept this official purchase order for inventory replenishment.</p>
          
          <table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
            <tr style="background-color: #f8fafc; border-bottom: 2px solid #e2e8f0;">
              <th style="padding: 10px; text-align: left;">Item Details</th>
              <th style="padding: 10px; text-align: right;">Value</th>
            </tr>
            <tr>
              <td style="padding: 8px; border-bottom: 1px solid #edf2f7;"><strong>Product Name:</strong></td>
              <td style="padding: 8px; border-bottom: 1px solid #edf2f7; text-align: right;">${productName}</td>
            </tr>
            <tr>
              <td style="padding: 8px; border-bottom: 1px solid #edf2f7;"><strong>SKU:</strong></td>
              <td style="padding: 8px; border-bottom: 1px solid #edf2f7; text-align: right;">${sku}</td>
            </tr>
            <tr>
              <td style="padding: 8px; border-bottom: 1px solid #edf2f7;"><strong>Order Quantity:</strong></td>
              <td style="padding: 8px; border-bottom: 1px solid #edf2f7; text-align: right;">${quantity} units</td>
            </tr>
            <tr>
              <td style="padding: 8px; border-bottom: 1px solid #edf2f7;"><strong>Unit Cost:</strong></td>
              <td style="padding: 8px; border-bottom: 1px solid #edf2f7; text-align: right;">$${Number(unitCost).toFixed(2)}</td>
            </tr>
            <tr style="font-weight: bold; background-color: #eff6ff;">
              <td style="padding: 10px; color: #1e40af;"><strong>Total Order Amount:</strong></td>
              <td style="padding: 10px; color: #1e40af; text-align: right;">$${Number(totalCost).toFixed(2)}</td>
            </tr>
          </table>

          <p>Please confirm receipt of this order and reply with estimated delivery details.</p>
          <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 20px 0;" />
          <p style="font-size: 12px; color: #64748b;">This email was automatically generated by StockPilot Inventory Restock Agent.</p>
        </div>
      `
    };

    const info = await mailer.sendMail(mailOptions);
    logger.info(`📧 Purchase Order Email dispatched to ${supplierEmail}:`, info.messageId || info.response || 'Dispatched');
    return { success: true, info };
  } catch (error) {
    logger.warn(`📧 SMTP dispatch timed out/failed for ${supplierEmail}: ${error.message}`);
    return { success: false, error: error.message };
  }
};
